SELECT * FROM TAB;

DROP TABLE "BASKET";

DROP SEQUENCE BASKET_SEQ;--SEQ삭제
CREATE SEQUENCE BASKET_SEQ;--SEQ만들기

CREATE TABLE BASKET(
	BASKET_SEQ NUMBER UNIQUE,
	MYID VARCHAR2(500) NOT NULL,
	PNAME VARCHAR2(500) NOT NULL,
	PID NUMBER NOT NULL,
	PRICE NUMBER NOT NULL,
	AMOUNT NUMBER NOT NULL
);

INSERT INTO BASKET
VALUES(BASKET_SEQ.NEXTVAL, 'kh', '도시락', 9, 1, 1);

SELECT BASKET_SEQ, MYID, PNAME, PID, PRICE, AMOUNT
		FROM BASKET
		WHERE BASKET_SEQ IN(1,2);

SELECT * FROM BASKET;
-----------------------------
DROP TABLE "PRODUCT";

CREATE TABLE "PRODUCT" (
   "PID"   NUMBER      UNIQUE,
   "PNAME"   VARCHAR2(100)      NOT NULL,
   "PPRICE"   NUMBER      NOT NULL, 
   "DESCRIPTION"   VARCHAR2(50)      NOT NULL,
   "PCOMPANY"   VARCHAR2(30)     
);

INSERT INTO PRODUCT VALUES(0,'현미닭가슴살영양밥&두부스테이크   ',4300,'체중조절 도시락 식단','꾹도시락');
INSERT INTO PRODUCT VALUES(1,'다섯가지나물밥&너비아니      ',4300,'체중조절 도시락 식단','꾹도시락');
INSERT INTO PRODUCT VALUES(2,'호박퀴노아영양밥&비프스테이크   ',4300,'체중조절 도시락 식단','꾹도시락');
INSERT INTO PRODUCT VALUES(3,'고구마현미영양밥&닭가슴살스테이크',4300,'체중조절 도시락 식단','꾹도시락');
INSERT INTO PRODUCT VALUES(4,'곤드레밥 & 오믈렛골드      ',4300,'체중조절 도시락 식단','꾹도시락');
INSERT INTO PRODUCT VALUES(5,'리얼 쉬림프 토핑  샐러드      ',5300,'토핑 샐러드 1팩','아임웰');
INSERT INTO PRODUCT VALUES(6,'롤치즈 & 고구마큐브 토핑 샐러드   ',5300,'토핑 샐러드 1팩','아임웰');
INSERT INTO PRODUCT VALUES(7,'훈제 닭가슴살 토핑 샐러드      ',5300,'토핑 샐러드 1팩','아임웰');
INSERT INTO PRODUCT VALUES(8,'델리 미트볼 토핑 샐러드      ',5300,'토핑 샐러드 1팩','아임웰');
INSERT INTO PRODUCT VALUES(9,'갈릭 케이준 치킨 토핑 샐러드      ',5300,'토핑 샐러드 1팩','아임웰');
INSERT INTO PRODUCT VALUES(10,'베이컨 시저 토핑 샐러드      ',5300,'토핑 샐러드 1팩','아임웰');

SELECT * FROM PRODUCT;
--------------------------------------------
DROP TABLE "SALEORDER";

CREATE TABLE "SALEORDER" (
   "ORDER_ID"   NUMBER      UNIQUE,
   "PID"   NUMBER      NOT NULL,
   "PNAME"   VARCHAR2(500)	NOT NULL,
   "MYID"   VARCHAR2(500)      NOT NULL,
   "ADDR"   VARCHAR2(4000)   NOT NULL,   -- 주문자가 다른 위치로 배달을 원할 경우
   "AMOUNT"   NUMBER      NOT NULL,
   "PRICE"   NUMBER      NOT NULL,
   "ORDER_DATE"   DATE      NOT NULL,
   "ORDER_STATE"   NUMBER      NOT NULL
);

DROP SEQUENCE ORDER_ID;--SEQ삭제
CREATE SEQUENCE ORDER_ID;--SEQ만들기

INSERT INTO SALEORDER VALUES(ORDER_ID.NEXTVAL, 0, '현미닭가슴살영양밥&두부스테이크   ', 'bbqq0108', '경기도', 1, 4000, SYSDATE, 1);

SELECT ORDER_STATE FROM SALEORDER WHERE ORDER_ID=1--주문번호에대한 주문상태 확인하기

SELECT * FROM SALEORDER;

UPDATE SALEORDER SET ORDER_STATE=4 WHERE ORDER_ID=1--주문 상태 변경



SELECT* FROM SALEORDER;-- 전체 출력
--------------------------------------------
DROP TABLE "REVIEW";

CREATE TABLE "REVIEW" (
   "R_NO"   NUMBER      NOT NULL,
   "PID"   NUMBER      NOT NULL,
   "R_STAR"   NUMBER      NULL,
   "R_WRITER"   VARCHAR2(1000)      NOT NULL,
   "R_TITLE"   VARCHAR2(3000)      NOT NULL,
   "R_CONTENT"   VARCHAR2(3000)      NOT NULL,
   "R_IMG"   VARCHAR2(100)      NULL,
   "R_DATE"   DATE      NOT NULL
);

DROP SEQUENCE R_NO;--SEQ삭제
CREATE SEQUENCE R_NO;--SEQ만들기

INSERT INTO REVIEW--리뷰 등록할 때
VALUES(R_NO.NEXTVAL, 0, 3, '지희', '제목', '테스트 게시물 내용입니다.', 'IMG', SYSDATE);


SELECT R_STAR FROM REVIEW WHERE PID=0;-- 상품 별 선택할 때 

SELECT * FROM REVIEW ORDER BY R_NO DESC;--리뷰 전체 출력할 때

DROP * FROM REVIEW WHERE R_NO=1;--리뷰 삭제할 때
--------------------------------------------

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
   "PID"
);

ALTER TABLE "SALEORDER" ADD CONSTRAINT "PK_SALEORDER" PRIMARY KEY (
   "ORDER_ID",
   "PID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
   "R_NO",
   "PID"
);

ALTER TABLE "SALEORDER" ADD CONSTRAINT "FK_PRODUCT_TO_SALEORDER_1" FOREIGN KEY (
   "PID"
)
REFERENCES "PRODUCT" (
   "PID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_PRODUCT_TO_REVIEW_1" FOREIGN KEY (
   "PID"
)
REFERENCES "PRODUCT" (
   "PID"
);

