DROP SEQUENCE FOODSEQ;
DROP SEQUENCE EXSEQ;

DROP TABLE "INBODY";
DROP TABLE "FOODCALORIE";
DROP TABLE "EXCALORIE";
DROP TABLE "CALORIEDIARY";

CREATE SEQUENCE FOODSEQ;
CREATE SEQUENCE EXSEQ;

CREATE TABLE "LOGINBOARD" (
	"MYID"	VARCHAR2(100)		NOT NULL,
	"MYPW"	VARCHAR2(100)		NOT NULL,
	"MYNAME"	VARCHAR2(100)		NOT NULL,
	"MYGENDER"	VARCHAR2(2)		NOT NULL,
	"MYBIRTHDAY"	NUMBER(6)		NOT NULL,
	"MYADDR"	VARCHAR2(4000)		NOT NULL,
	"MYPHONE"	VARCHAR2(20)		NOT NULL,
	"MYEMAIL"	VARCHAR2(100)		NOT NULL,
	"MYENABLED"	VARCHAR2(2)		NOT NULL,
	"MYROLE"	VARCHAR2(100)		NOT NULL
);

CREATE TABLE "INBODY" (
	"MYID"	VARCHAR2(100)		NOT NULL,
	"WEIGHT"	NUMBER		NULL,
	"HEIGHT"	NUMBER		NULL,
	"BMI"	NUMBER		NULL,
	"METABOLISM"	NUMBER		NULL
);

CREATE TABLE "FOODCALORIE" (
	"FOODNO"	NUMBER		NOT NULL,
	"FOOD_GROUP"	VARCHAR2(500)		NOT NULL,
	"FOODNAME"	VARCHAR2(500)		NOT NULL,
	"SERVINGSIZE"	NUMBER		NOT NULL,
	"CALORIE"	NUMBER		NOT NULL
);

CREATE TABLE "EXCALORIE" (
	"EXNO"	NUMBER		NOT NULL,
	"EXNAME"	VARCHAR2(500)		NOT NULL,
	"COMMON"	NUMBER		NOT NULL,
	"CONSUMED_CALORIE"	NUMBER		NOT NULL
);

CREATE TABLE "CALORIEDIARY" (
	"MDATE"	VARCHAR2(8)		NOT NULL,
	"MYID"	VARCHAR2(100)		NOT NULL,
	"TOTALCAL"	NUMBER		NULL,
	"TOTALMETA"	NUMBER		NULL,
	"REGDATE"	DATE		NOT NULL
);

ALTER TABLE "LOGINBOARD" ADD CONSTRAINT "PK_LOGINBOARD" PRIMARY KEY (
	"MYID"
);

ALTER TABLE "INBODY" ADD CONSTRAINT "PK_INBODY" PRIMARY KEY (
	"MYID"
);

ALTER TABLE "CALORIEDIARY" ADD CONSTRAINT "PK_CALORIEDIARY" PRIMARY KEY (
	"MDATE",
	"MYID"
);

ALTER TABLE "INBODY" ADD CONSTRAINT "FK_LOGINBOARD_TO_INBODY_1" FOREIGN KEY (
	"MYID"
)
REFERENCES "LOGINBOARD" (
	"MYID"
);

ALTER TABLE "CALORIEDIARY" ADD CONSTRAINT "FK_INBODY_TO_CALORIEDIARY_2" FOREIGN KEY (
	"MYID"
)
REFERENCES "INBODY" (
	"MYID"
);

SELECT * FROM LOGINBOARD;
SELECT * FROM FOODCALORIE;
SELECT * FROM INBODY;
SELECT * FROM EXCALORIE;
SELECT * FROM CALORIEDIARY;

INSERT INTO LOGINBOARD VALUES('ADMIN','ADMIN123','ADMIN','M',900909,'서울특별시','010-1234-5678','ADMIN@ADMIN.COM','Y','ADMIN');
INSERT INTO LOGINBOARD VALUES('USER','USER123','USER','W',901010,'경기도','010-1234-5678','USER@USER.COM','Y','USER');
INSERT INTO LOGINBOARD VALUES('KHQ','KHQ123','KHQ','M',950505,'인천광역시','010-9876-5432','KH@KH.COM','Y','USER');
INSERT INTO INBODY VALUES('ADMIN', NULL, NULL, NULL, NULL);
